import Head from "next/head";
import Form from "../components/Form";
import useSWR from "swr";
import styled from "styled-components";
import { StyledLink } from "../components/StyledLink.js";
import CreateServicePage from "./createService";
import UpdateServicePage from "./services/[id]/updateService";

const List = styled.ul`
  list-style: none;
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 1rem;
  padding-left: 0;
`;

const ListItem = styled.li`
  position: relative;
  width: 100%;
`;
const FixedLink = styled(StyledLink)`
  position: fixed;
  bottom: 50px;
  right: 50px;
`;

export default function Home() {
  const { data } = useSWR("/api/services", { fallbackData: [] });

  return (
    <>
      <Head>
        <title>Parcelio App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      <main>
        {/* <CreateServicePage /> */}
        {/* <UpdateServicePage /> */}
        <List role="list">
          {data.map((service) => {
            return (
              <ListItem key={service._id}>
                {service.firstName} {service.lastName} {service.userName}
              </ListItem>
            );
          })}
        </List>
      </main>
    </>
  );
}
